// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALiH0V4ha--x6QwcCrI9I8kS1JAwIjXSc',
    appId: '1:406140436610:web:3037ac575556a2050ff49b',
    messagingSenderId: '406140436610',
    projectId: 'financas-360-br',
    authDomain: 'financas-360-br.firebaseapp.com',
    storageBucket: 'financas-360-br.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm2m6_qaCMkoc96Hm1GwURzQ4xe-Jwe80',
    appId: '1:406140436610:android:f1bbeb233bcc683b0ff49b',
    messagingSenderId: '406140436610',
    projectId: 'financas-360-br',
    storageBucket: 'financas-360-br.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQnDkua0nh6dSK3ppCoQGChvQHeVnIyQg',
    appId: '1:406140436610:ios:2c5b079d640301e70ff49b',
    messagingSenderId: '406140436610',
    projectId: 'financas-360-br',
    storageBucket: 'financas-360-br.appspot.com',
    iosBundleId: 'com.example.financas360',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQnDkua0nh6dSK3ppCoQGChvQHeVnIyQg',
    appId: '1:406140436610:ios:17902dad63e451ab0ff49b',
    messagingSenderId: '406140436610',
    projectId: 'financas-360-br',
    storageBucket: 'financas-360-br.appspot.com',
    iosBundleId: 'com.example.financas360.RunnerTests',
  );
}
